# Generated by Django 3.2.9 on 2022-01-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('question_language', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('cz', 'Czech'), ('es', 'Spanish')], default='en', max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('answer_language', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('cz', 'Czech'), ('es', 'Spanish')], max_length=200)),
                ('is_noun', models.BooleanField(default=True)),
                ('article', models.CharField(max_length=200)),
            ],
        ),
    ]
