# Generated by Django 3.2.9 on 2022-01-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
