# Generated by Django 3.2.9 on 2022-01-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_app', '0003_auto_20220108_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='slug',
            field=models.CharField(default='german_animals', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionset',
            name='answer_language',
            field=models.CharField(choices=[('EN', 'English'), ('DE', 'German'), ('CZ', 'Czech'), ('ES', 'Spanish')], max_length=200),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='questions_language',
            field=models.CharField(choices=[('EN', 'English'), ('DE', 'German'), ('CZ', 'Czech'), ('ES', 'Spanish')], default='EN', max_length=200),
        ),
    ]
