# Generated by Django 3.2.9 on 2022-01-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_app', '0005_alter_question_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='article',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
