# Generated by Django 3.2.9 on 2022-01-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_app', '0006_alter_question_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionset',
            name='answer_language',
            field=models.CharField(choices=[('english', 'English'), ('german', 'German'), ('czech', 'Czech'), ('spanish', 'Spanish')], max_length=200),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='questions_language',
            field=models.CharField(choices=[('english', 'English'), ('german', 'German'), ('czech', 'Czech'), ('spanish', 'Spanish')], default='english', max_length=200),
        ),
    ]
